version: 2.1
orbs:
  queue: eddiewebb/queue@1.6.4
jobs:
  test:
    working_directory: ~/terraform-aws-network-load-balancer
    docker:
      - image: ruby:3.1.1
    steps:
      - checkout
      - run: ./scripts/ci/common/install-git-crypt.sh
      - run: ./scripts/ci/common/install-orb-deps.sh
      - queue/until_front_of_line:
          consider-branch: false
      - run: ./scripts/ci/steps/test.sh
  merge_pull_request:
    working_directory: ~/terraform-aws-network-load-balancer
    docker:
      - image: ruby:3.1.1
    steps:
      - checkout
      - run: ./scripts/ci/common/install-git-crypt.sh
      - run: ./scripts/ci/common/install-gpg-key.sh
      - run: ./scripts/ci/common/configure-git.sh
      - run: ./scripts/ci/steps/merge-pull-request.sh
  prerelease:
    working_directory: ~/terraform-aws-network-load-balancer
    docker:
      - image: ruby:3.1.1
    steps:
      - checkout
      - run: ./scripts/ci/common/install-git-crypt.sh
      - run: ./scripts/ci/common/install-gpg-key.sh
      - run: ./scripts/ci/common/configure-git.sh
      - run: ./scripts/ci/steps/prerelease.sh
  release:
    working_directory: ~/terraform-aws-network-load-balancer
    docker:
      - image: ruby:3.1.1
    steps:
      - checkout
      - run: ./scripts/ci/common/install-git-crypt.sh
      - run: ./scripts/ci/common/install-gpg-key.sh
      - run: ./scripts/ci/common/configure-git.sh
      - run: ./scripts/ci/steps/release.sh
workflows:
  version: 2
  pipeline:
    jobs:
      - test:
          filters:
            branches:
              only:
                - main
                - /^dependabot.*/
      - prerelease:
          requires:
            - test
          filters:
            branches:
              only: main
      - merge_pull_request:
          requires:
            - test
          filters:
            branches:
              only: /^dependabot.*/
      - hold:
          type: approval
          requires:
            - prerelease
          filters:
            branches:
              only: main
      - release:
          requires:
            - hold
          filters:
            branches:
              only: main
