---
region: 'eu-west-2'

component: 'test'
deployment_identifier: "%{hiera('deployment_identifier')}"

work_directory: 'build'
configuration_directory: "%{hiera('work_directory')}/%{hiera('source_directory')}"

domain_name: 'greasedscone.uk'

allowed_cidrs:
  - '0.0.0.0/0'
egress_cidrs:
  - '10.0.0.0/8'
  - '192.168.0.0/16'

vpc_cidr: '10.1.0.0/16'
availability_zones:
  - "eu-west-2a"
  - "eu-west-2b"

dependencies:
  - "other"
  - "stuff"

public_zone_id: 'Z4Q2X3ESOZT4N'
private_zone_id: 'Z2CDAFD23Q10HO'

enable_cross_zone_load_balancing: 'no'

idle_timeout: 120

include_public_dns_record: 'no'
include_private_dns_record: 'yes'

expose_to_public_internet: 'no'
use_https: 'no'

target_group_port: 3023
target_group_type: 'instance'
target_group_protocol: 'TCP'

health_check_port: 'traffic-port'
health_check_protocol: 'TCP'
health_check_healthy_threshold: 5
health_check_unhealthy_threshold: 5
health_check_interval: 30

listener_port: 443
listener_protocol: 'TLS'
